

services:
  # ── Databases ──────────────────────────────────
  auth-postgres:
    image: postgres:16-alpine
    container_name: fb_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: auth_db 
    volumes:
      - auth-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: fb_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Redis ──────────────────────────────────────
  redis:
    image: redis:7-alpine
    container_name: fb_redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Kafka ──────────────────────────────────────
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: fb_kafka
    ports:
      - "9092:9092"

    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - kafka_data:/var/lib/kafka/data

  # ── Kafka UI ───────────────────────────────────
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: fb_kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

  # ── Services ───────────────────────────────────

  auth-service:
    build: 
      context: . 
      dockerfile: apps/auth-service/Dockerfile
    container_name: fb_auth
    ports:
      - "3001:3001"
    environment:
      - GRPC_PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres123@auth-postgres:5432/auth_db?schema=public
      - REDIS_HOST=redis
      - JWT_SECRET=supersecret
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      auth-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

volumes:
  auth-postgres:
  mongo_data:
  redis_data:
  kafka_data: