
services:
  # ── Databases ──────────────────────────────────
  auth-postgres-primary:
    image: postgres:17
    container_name: product_postgres_auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: auth_db
    volumes:
      - auth-postgres-primary_data:/var/lib/postgresql/data

  user-postgres-primary:
    image: postgres:17
    container_name: product_postgres_user
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: user_db
    volumes:
      - user-postgres-primary_data:/var/lib/postgresql/data

  media_mongo_db_primary:
    image: mongo:7
    container_name: product_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    volumes:
      - media_mongo_primary_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Redis ──────────────────────────────────────
  auth_redis:
    image: redis:7-alpine
    container_name: product_redis_auth
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    volumes:
      - auth_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  user_redis:
    image: redis:7-alpine
    container_name: product_redis_user
    ports:
      - "6378:6379"
    command: >
      redis-server
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    volumes:
      - user_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_gateway_redis:
    image: redis:7-alpine
    container_name: product_redis_api_gateway
    ports:
      - "6377:6379"
    command: >
      redis-server
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    volumes:
      - api_gateway_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Kafka ──────────────────────────────────────
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: product_kafka
    ports:
      - "9092:9092"

    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - kafka_data:/var/lib/kafka/data

  # ── Kafka UI ───────────────────────────────────
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: product_kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

  # ── Services ───────────────────────────────────

  # auth-service:
  #   build:
  #     context: .
  #     dockerfile: apps/auth-service/Dockerfile
  #   container_name: product_auth
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - GRPC_PORT=3001

  #     # Write operations
  #     - AUTH_DB_PRIMARY_UR=postgresql://postgres:postgres123@auth-postgres-primary:5432/auth_db
  #     - AUTH_REDIS_HOST=auth_redis
  #     - JWT_ACCESS_SECRET=supersecret
  #     - KAFKA_BROKERS=kafka:9092

  #   depends_on:
  #     auth-postgres-primary:
  #       condition: service_started
  #     auth_redis:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_healthy


  # user-service:
  #   build:
  #     context: .
  #     dockerfile: apps/user-service/Dockerfile
  #   container_name: product_user
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     - GRPC_PORT=3002

  #     # Write operations
  #     - USER_DB_PRIMARY_UR=postgresql://postgres:postgres123@user-postgres-primary:5432/user_db
  #     - USER_REDIS_HOST=user_redis
  #     - JWT_ACCESS_SECRET=supersecret
  #     - KAFKA_BROKERS=kafka:9092

  #   depends_on:
  #     auth-postgres-primary:
  #       condition: service_started
  #     user_redis:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_healthy

volumes:
  auth-postgres-primary_data:
  user-postgres-primary_data:
  media_mongo_primary_data:
  auth_redis_data:
  user_redis_data:
  api_gateway_redis_data:
  kafka_data:
