# --- STAGE 1: Build Stage ---
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate --schema=./apps/api-gateway/prisma/schema.prisma

RUN npm run build api-gateway

RUN npm prune --production


FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/api-gateway/prisma ./apps/api-gateway/prisma
COPY --from=builder /app/dist ./dist

EXPOSE 3001

CMD ["node", "dist/apps/api-gateway/main.js"]